
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Kukumalu3312
    url: jdbc:mysql://rm-bp1bm22j5h4hj62q0go.mysql.rds.aliyuncs.com:3306/lv-ordering?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
server:
  servlet:
    context-path: /sell
  port: 8081