
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Kukumalu3312
    url: jdbc:mysql://rm-bp1bm22j5h4hj62q0go.mysql.rds.aliyuncs.com:3306/lv-ordering?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
  port: 8081