
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.110/ordering?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
server:
  servlet:
    context-path: /sell
  port: 8080